### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by richardherbert**
Added note about using Homebrew to upgrade CommandBox on Mac/*Unix.

### CODE REVIEW

**Comment by bdw429s** [comment]
Thanks @richardherbert Does Homebrew not have an update command to do it in one step?  I'm wondering if the uninstall will remove anything that we don't want to lose.

**Comment by richardherbert** [comment]
I have had issues in the past with `upgrade`. You're supposed to...

```bash
brew update
brew upgrade commandbox
```

...but the last couple of CommandBox releases I've used uninstall/install and don't seem to have felt any ill effects. 

Maybe I'll ask the collective hive mind on Slack.

**Comment by bdw429s** [comment]
Please do check on that.  If there's issues using the `upgrade` command, I've not heard of them and I'd like to fix it so it works correctly.  cc/ @jclausen

**Comment by richardherbert** [comment]
For the record, for CommandBox 4.5.0 I did:

```brew upgrade commandbox```

Which updated my HomeBrew before it upgraded my CommandBox.

I've still got some more tests to do but all seems find for now. Maybe the issues that @jclausen and I experienced have gone away?

I'm happy to revert my change to the docs if you want?

**Pull request merged**
